odu-emse/emseAPI

.circleci/config.yml

Initialized CircleCI testing

---

prisma/schema.prisma
src/pos/pos.service.ts
src/user/user.service.ts
tsconfig.json

Features:
-  avoid duplicate users with error messages
-  delete users with error messages
I don't know if it's necessary to do error checking on updating user info?
Then also why do we have two password fields in the database?
my thought process: upon user registration, we can confirm the password match then just save only one.
I will be diving deep into tokenization. I also noticed the password now is saved has the hashed values. What do we need the tokenization for exactly?

Userchecks

---

src/user/user.service.ts

Adds the dob to the list of attributes being updated in the "updateUser" mutation.

Add dob to userUpdate mutation

---

src/program/program.resolver.ts
src/user/user.resolver.ts

refactor: Removed duplicate error throws and catches from resolvers

---

gql/graphql.ts
src/user/schema.graphql
src/user/user.service.ts

Removed the include in the instructorProfile query that was causing a ts error.

Remove redundant include in instructor profile query

---

src/auth/auth.resolver.ts
src/auth/auth.service.ts
src/auth/schema.graphql

Add a new endpoint which accepts a refresh token and creates a new ID token

Add endpoint for refreshing the token.

---

src/pos/schema.graphql

Added documentation for plan of study

documentation of pos

---

gql/graphql.ts
prisma/dbml/schema.dbml
prisma/schema.prisma
src/program/program.resolver.ts
src/program/program.service.ts
src/program/program.spec.ts
src/program/schema.graphql

Verified ALMP-440
Verified ALMP-442
Verified ALMP-445
Verified ALMP-480

:sparkles: (program): Added collection feature

---

gql/graphql.ts
prisma/dbml/schema.dbml
prisma/schema.prisma
src/pos/pos.service.ts
src/program/program.resolver.ts
src/program/program.service.ts
src/program/program.spec.ts
src/program/schema.graphql

1. Implemented many-to-many relation in schema for Module and Courses model
2. Removed ModuleInCourse model and existing queries
3. Modified pairCourseModule and unpairCourseModule queries
4. Removed parentCourses

ALMP-407: Remove ModuleInCourse Model

---

src/community/community.spec.ts

1. Handled a thread and ensured that the original vote has increased by one after running upVote service

ALMP-485: Created test case for upVote service

---

.github/workflows/master_emse-api.yml
.gitignore
docs.config.yml
gql/graphql.ts
package.json
prisma/dbml/schema.dbml
prisma/schema.prisma
src/community/community.resolver.ts
src/community/community.spec.ts
src/program/program.resolver.ts
src/program/program.service.ts
src/program/program.spec.ts
src/program/schema.graphql
yarn.lock

:sparkles: (compound): Added Support for multi-value-filter on scalar fields

---

gql/graphql.ts
prisma/dbml/schema.dbml
prisma/schema.prisma
src/program/program.resolver.ts
src/program/program.service.ts
src/program/schema.graphql

Lessons now relate to a content model. This will hold the link to the content as well as its type.

Added Content Model

---

src/community/community.service.ts
src/community/community.spec.ts
src/pos/index.ts

1. Ensured test cases were passed
2. Implemented prisma validator to create a reusable include statement

Created a reusable class validator in community service

---

src/user/user.service.ts

1. Ensured test cases were passed
2. Implemented prisma validator to create a reusable include statement

Created a reusable class validator in user service

---

src/pos/pos.service.ts

1. Ensured that there were no errors in jest
2. Implemented prisma validator type

Created a reusable class validator in PoS service

---

gql/graphql.ts
src/program/program.service.ts
src/program/schema.graphql

1. Defined objectives property in graphql
2. Implemented scalar list field
3. Tested query search for objectives

Added objective property to search parameter

---

src/program/program.spec.ts

:white_check_mark: (program): Fixed failing test cases caused by query refactor

---

prisma/dbml/schema.dbml
prisma/schema.prisma
src/app.module.ts
src/program/program.service.ts

1. Added cascading referential actions to modules
2. If module is deleted, collections and lessons will be deleted
3. Tested to ensure that cascading delete works
4. Danny and Matt changes to createLesson service

Added cascading deletes to modules

---

src/program/program.resolver.ts
src/program/program.spec.ts

1. Made UserRole argument to optional
2. Renamed Prisma.ModuleCreateInput to NewModule due to compatibility error of between ModuleCreateInput and NewModule

Fixed failing test cases in UserRole feature

---

src/community/community.resolver.ts
src/community/community.service.ts
src/community/community.spec.ts

feat(community): Timestamp of parent thread updates on comment addition

---

gql/graphql.ts
src/program/program.resolver.ts
src/program/program.service.ts
src/program/program.spec.ts
src/program/schema.graphql

1. Modified service file to have one instance of collection instead of collection and collections
2. Added id as a query parameter 
3. Modified test cases that gave errors from deleted "collections" service

Created Compound Query for Collection

---

gql/graphql.ts
prisma/dbml/schema.dbml
prisma/schema.prisma
src/program/program.service.ts
src/program/schema.graphql

1. Added content and assignment types to Assignment model and AssignmentResult model in prisma schema
2. Modified service parameters for Assignment service and AssignmentResult service
3. Added required contentType, contentURL, and acceptedTypes in NewAssignment model in graphql schema
4. Added submissionURL and fileType in NewAssignmentResult model in graphql schema

Added content to assignment and assignmentResult

---

src/progress/progress.spec.ts

1. Basic CRUD test cases were already covered
3. After waiving module, check to see if the completion bool is set to true and if status is 100

Created test case for waiving modules

---

src/progress/progress.spec.ts

1. Removed '?' from result object in .spec

Added check parameter for result being undefined

---

src/community/community.service.ts
src/community/community.spec.ts

Alongside the fix, I created a test case to make sure the includes was created successfully. Made some modifications to the upvote thread test case as well but that needs to be addressed in ALMP-633

fix(threads): Fixed author relation not populating in comments

---

src/community/community.spec.ts
src/direct-message/direct-message.spec.ts
src/progress/progress.spec.ts

1. Wrote test cases for querying and mutations of Direct Messaging
More details on the some of the logic:
1. Imported Utils Class for fake data
3. If member is 0, should not exits, should have at least one
4. Mapped over message array, checked if author of messages is inside the group members. 
Subscriptions resolvers were not tested due to complications with AsyncIterators.

Write test cases for Direct Messaging Features

---

gql/graphql.ts
prisma/dbml/schema.dbml
prisma/schema.prisma
src/community/community.resolver.ts
src/community/community.service.ts
src/community/community.spec.ts
src/community/schema.graphql
src/program/program.resolver.ts
src/program/program.service.ts
src/program/schema.graphql
src/user/user.service.ts

1. Removed all references to lessons and all includes that were breaking type safety
2. Created a list of string property called topics
3. Updated CRUD operations to run on topics too (update, search by param, create)
4. Created test case for topic based parameter search (partial array element is still not supported)

feat(community): Updated thread schema to have topics and no references to lessons

---

gql/graphql.ts
prisma/dbml/schema.dbml
prisma/schema.prisma
src/community/community.resolver.ts
src/community/community.service.ts
src/community/community.spec.ts
src/community/schema.graphql
src/program/program.resolver.ts
src/program/program.service.ts
src/program/schema.graphql
src/progress/schema.graphql
src/user/user.service.ts

Merge **AFTER** merging ALMP-674 (#478)

feat(program): Create model to track lesson progress
